# Site settings
title: Vinser GitHub Pages
author:
  name: Serguei Vine
  email: vinser@outlook.com
description: "FLibGoLite - Just enough for free OPDS"

markdown: GFM
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme