title: Vinser GitHub Pages
description: "FLibGoLite - Just enough for free OPDS"
# author:
#   name: Serguei Vine
#   email: vinser@outlook.com

markdown: GFM
theme: minima

header_pages:
  - index.md
  - flibgolite.md
  - pixyne.md
  - burnfix.md
