# Site settings
title: Vinser GitHub Pages
author:
  name: Serguei Vine
  email: vinser@outlook.com
description: "Vinser on GH-Pages."

# Build settings
# remote_theme: jekyll/minima

show_downloads: true
# theme: jekyll-theme-slate
remote_theme: pages-themes/leap-day@v0.2.0
# plugins:
# - jekyll-remote-theme