title: Vinser GitHub Pages
description: My landing site
theme: just-the-docs
author:
  name: Serguei Vine
#   email: vinser@outlook.com

url: https://github.com/vinser/vinser.github.io
# markdown: GFM
