url: https://github.com/vinser/vinser.github.io
title: Vinser GitHub Pages
description: My landing site
author:
  name: Serguei Vine
#   email: vinser@outlook.com

theme: minima
# markdown: GFM

header_pages:
  - index.md
  - flibgolite.md
  - pixyne.md
  - burnfix.md
